spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ysun1030
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # Spring Boot2?? default DBCP? hikariCP???.
      maximum-pool-size: 20             # pool? ?? ??? ?? connection ?


  sql:
    init:
      mode: always # ?? ??? ?? classpath? sql?? ????? ??
      continue-on-error: true # ?? ??? sql?? ??? ? ?? ???? ?? ??
      data-locations: classpath:sql/data.sql # ?? ??? dml sql?? ??? ?? ? ?? ??
      schema-locations: classpath:sql/schema.sql # ?? ??? ddl sql?? ??? ?? ? ?? ??

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true


batch:
  job:
    enabled: false # ??? true? Spring Boot ?? ? ???? ?? Job?? ?????.
  jdbc:
    # Batch? ???? SQL ??? ????? ?????. ????? ???? ????? ?????, always ??? ?? ???? ???? ?? ????? ? ????.
    # ?? ??? ???? ???? ???.
    initialize-schema: always

